### ISSUE TITLE
Antimatter Bomb crash

### ISSUE THREAD

**Issue by valveo** [CD4017BE/InductiveAutomation#1]
Ok, So I was testing your mod and wanted to try bomb, because who doesnt love them.
Went far from all building and placed bomb, and redstone torch right next to it, then run away.
I was expecting big hole, but what really happend was this.
Whole server crashed. I mean not just minecraft server, but whole server. Never happend before.
After restart I logged in game and same happend. And then again. I had to revert to earlier backup and I was able to login.
But no crash report, nothing at all. No errors in log. So you bomb is great, but i think its too powerful.
I hope my hosting company doesnt come to tell me that I blow up their server room.

I hope you can find something that might help to figure out what is causing it. I can only provide you mod list of my server, some of them is clientside mods, because im lazy to clean them up, but well. Here it is:

AuraCascade-592.jar
Bagginses-1.8.9-2.1.5b.jar
bdlib-1.10.0.31-mc1.8.9.jar
BetterAchievements-1.8.9-0.1.1.jar
BetterBuildersWands-0.5.1-1.8.9r83+04d387c.jar
BetterThanBunnies-1.8.9-1.0.1.jar
BloodMagic-1.8.9-2.0.0-19.jar
Bookshelf-API-1.8.9-2.3.6.jar
Botania-unofficial.r1.8-299.jar
buildcraft-7.2.0.jar
buildcraft-compat-7.2.0.jar.disabled
BuildingBricks-1.8.9-1.4.1.jar
CD4017BE_lib-1.8.9-3.0.1.jar
Chameleon-1.8.9-0.2.1.jar
Charset-0.2.4-85343416c852285a595c4c6e.jar
Chisel-MC1.8.9-0.0.2.6.jar
chiselsandbits-mc1.8.9-v1.8.11.jar
CompassCoords-1.8.9-0.2.6.jar
ComputerCraft1.78.jar
craftingtweaks-mc1.8.9-3.0.52.jar
CraftTweaker-1.8.8-3.0.2.jar
denseores-1.8-alpha-2.0.0.jar
DynamicSurroundings-1.8.9-2.0.4.10.jar
EnderTanks-1.8.9-1.2.1.jar
enderutilities-1.8.9-0.5.0.jar
extrautils2-1.8.9-alpha-0.0.1.jar
ezstorage-1.8.9-1.2.6.jar
FastLeafDecay-1.8-1.6.jar
flatcoloredblocks-mc1.8.9-v1.8.jar
FTBLib-1.8.9-2.0.2.jar
FTBUtilities-1.8.9-2.0.2.jar
Furnus-1.8.9-1.73.jar
generators-0.9.19.9-mc1.8.9.jar
graves-1.8.9-b45-universal.jar
hopperducts-mc1.8.8-1.4.6.jar
HydCraft-1.8.9-3.1.79-universal.jar
IGW-Mod-1.8.9-1.2.4-4-universal.jar
InductiveAutomation-1.8.9-4.0.0.jar
intangible-1.8.9-0.0.25.jar
inventorysorter-1.8.9-0.7.4+26.jar
ironchest-1.8.9-6.0.125.770.jar
jei_1.8.9-2.28.7.174.jar
journeymap-1.8.9-5.1.5-unlimited.jar
JustEnoughResources-1.8.9-0.4.0.jar
k4lib-1.8.9-1.0.16-universal.jar
Mantle-1.8.9-0.8.2.jar
mcjtylib-1.8.9-1.8.1beta8.jar
MCMultiPart-1.0.8-universal.jar
MmmMmmMmmMmm-1.9b.jar
Morpheus-1.8.9-2.0.58.jar
NeoTech-1.8.9-2.4.1.jar
OreDictionaryConverter-1.7.2.jar
PlayerRugs-1.8.8-1.2.0.jar
PneumaticCraft-1.8.9-1.13.8-12-universal.jar
pressure-1.3.0.25-mc1.8.9.jar
ProgressiveAutomation-1.8.9-1.6.35.jar
Psi-beta-23.jar
RandomThings-MC1.8.9-3.6.4.jar
rftools-1.8.9-4.22beta31.jar
ShetiPhianCore-1.8.9-3.1.0.jar
simpleretrogen-1.8.9-2.2.2+3.jar
StorageDrawers-1.8.9-2.4.4.jar
TConstruct-1.8.9-2.1.0.jar
Thaumcraft-1.8.9-5.2.2.jar
ThaumicInfusion-1.8.9-4.82.jar
Waila-1.6.0-B3_1.8.8.jar
Wawla-1.4.7-1.8+.jar

**Comment by valveo** [comment]
Actually I get crash log now, when tried single player:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 20.3.2016 5:01
Description: Ticking block entity

java.lang.IllegalArgumentException: Duplicate id value for 2!
    at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:73)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.func_70088_a(EntityAntimatterExplosion1.java:71)
    at net.minecraft.entity.Entity.<init>(Entity.java:183)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.<init>(EntityAntimatterExplosion1.java:51)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.<init>(EntityAntimatterExplosion1.java:56)
    at cd4017be.automation.TileEntity.AntimatterBomb.func_73660_a(AntimatterBomb.java:48)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:73)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.func_70088_a(EntityAntimatterExplosion1.java:71)
    at net.minecraft.entity.Entity.<init>(Entity.java:183)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.<init>(EntityAntimatterExplosion1.java:51)
    at cd4017be.automation.Entity.EntityAntimatterExplosion1.<init>(EntityAntimatterExplosion1.java:56)
    at cd4017be.automation.TileEntity.AntimatterBomb.func_73660_a(AntimatterBomb.java:48)

-- Block entity being ticked --
Details:
    Name: tile.antimatterBombF // cd4017be.automation.TileEntity.AntimatterBomb
    Block type: ID #1405 (tile.antimatterBombF // cd4017be.lib.TileBlock)
    Block data value: 6 / 0x6 / 0b0110
    Block location: World: (2121,8,194), Chunk: (at 9,0,2 in 132,12; contains blocks 2112,0,192 to 2127,255,207), Region: (4,0; contains chunks 128,0 to 159,31, blocks 2048,0,0 to 2559,255,511)
    Actual block type: ID #1405 (tile.antimatterBombF // cd4017be.lib.TileBlock)
    Actual block data value: 6 / 0x6 / 0b0110
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['HNInfo'/1715489, l='New World', x=2081,22, y=9,49, z=113,70]]
    Chunk stats: ServerChunkCache: 782 Drop: 0
    Level seed: -4709859883177227712
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: 2017,00,4,00,41,00 - World: (2017,4,41), Chunk: (at 1,0,9 in 126,2; contains blocks 2016,0,32 to 2031,255,47), Region: (3,0; contains chunks 96,0 to 127,31, blocks 1536,0,0 to 2047,255,511)
    Level time: 2300 game time, 2300 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 13192 (now: false), thunder time: 90172 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1748616400 bytes (1667 MB) / 4240441344 bytes (4044 MB) up to 4240441344 bytes (4044 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024M -Xmx4096M -XX:MaxPermSize=256M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 90 mods loaded, 90 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   CoreXU2{1} [CoreXU2](minecraft.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   aura{592} [Aura Cascade](AuraCascade-592.jar) 
    UCHIJAAAA   bagginses{2.1.5b} [Bagginses](Bagginses-1.8.9-2.1.5b.jar) 
    UCHIJAAAA   bdlib{1.10.0.31} [BD Lib](bdlib-1.10.0.31-mc1.8.9.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements](BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   betterbuilderswands{0.5.1} [Better Builder's Wands](BetterBuildersWands-0.5.1-1.8.9r83+04d387c.jar) 
    UCHIJAAAA   BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.1.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.8.9-alpha-0.0.1.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   intangible{0.0.25} [Intangible](intangible-1.8.9-0.0.25.jar) 
    UCHIJAAAA   JEI{2.28.7.174} [Just Enough Items](jei_1.8.9-2.28.7.174.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-19.jar) 
    UCHIJAAAA   bookshelfapi{2.3.6} [Bookshelf](Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAA   Thaumcraft{5.2.2} [Thaumcraft](Thaumcraft-1.8.9-5.2.2.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0} [BuildCraft](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0} [BC Builders](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0} [BC Transport](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0} [BC Energy](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0} [BC Silicon](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0} [BC Robotics](buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0} [BC Factory](buildcraft-7.2.0.jar) 
    UCHIJAAAA   buildingbrickscompatvanilla{1.8.9-1.4.1} [Building Bricks Vanilla Compat](BuildingBricks-1.8.9-1.4.1.jar) 
    UCHIJAAAA   buildingbricks{1.8.9-1.4.1} [Building Bricks](BuildingBricks-1.8.9-1.4.1.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   mcmultipart{1.0.8} [MCMultiPart](MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAA   CharsetLib{0.2.4} [‽](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetTweaks{0.2.4} [*](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetDrama{0.2.4} [!](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetWires{0.2.4} [+](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetAudio{0.2.4} [♫](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetStorage{0.2.4} [#](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetPipes{0.2.4} [|](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   CharsetGates{0.2.4} [&](Charset-0.2.4-85343416c852285a595c4c6e.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.11.jar) 
    UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords](CompassCoords-1.8.9-0.2.6.jar) 
    UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
    UCHIJAAAA   craftingtweaks{3.0.52} [Crafting Tweaks](craftingtweaks-mc1.8.9-3.0.52.jar) 
    UCHIJAAAA   crafttweaker{3.0.0} [crafttweaker](CraftTweaker-1.8.8-3.0.2.jar) 
    UCHIJAAAA   dsurround{2.0.4.10} [Dynamic Surroundings](DynamicSurroundings-1.8.9-2.0.4.10.jar) 
    UCHIJAAAA   ShetiPhianCore{3.1.0} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.1.0.jar) 
    UCHIJAAAA   EnderTanks{1.2.1} [EnderTanks](EnderTanks-1.8.9-1.2.1.jar) 
    UCHIJAAAA   enderutilities{0.5.0} [Ender Utilities](enderutilities-1.8.9-0.5.0.jar) 
    UCHIJAAAA   ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.6.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.8.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   furnus{1.73} [Furnus](Furnus-1.8.9-1.73.jar) 
    UCHIJAAAA   pressure{1.3.0.25} [Pressure Pipes](pressure-1.3.0.25-mc1.8.9.jar) 
    UCHIJAAAA   advgenerators{0.9.19.9} [Advanced Generators](generators-0.9.19.9-mc1.8.9.jar) 
    UCHIJAAAA   graves{1.8.9-b45-universal} [Graves Mod](graves-1.8.9-b45-universal.jar) 
    UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.16} [K4Lib](k4lib-1.8.9-1.0.16-universal.jar) 
    UCHIJAAAA   HydCraft{1.8.9-3.1.79} [Hydraulicraft](HydCraft-1.8.9-3.1.79-universal.jar) 
    UCHIJAAAA   IGWMod{1.2.4-4} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
    UCHIJAAAA   Automation{4.0.0} [Inductive Automation](InductiveAutomation-1.8.9-4.0.0.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap](journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources](JustEnoughResources-1.8.9-0.4.0.jar) 
    UCHIJAAAA   llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
    UCHIJAAAA   mantle{1.8.9-0.8.2.jenkins95} [Mantle](Mantle-1.8.9-0.8.2.jar) 
    UCHIJAAAA   mfs{2.1.0} [Minecraft Flight Simulator](Minecraft Flight Simulator-1.8.9-2.1.0.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.58} [Morpheus](Morpheus-1.8.9-2.0.58.jar) 
    UCHIJAAAA   MouseTweaks{2.6.0} [Mouse Tweaks](MouseTweaks-2.6.0-mc1.8.9.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct](TConstruct-1.8.9-2.1.0.jar) 
    UCHIJAAAA   neotech{2.4.1} [NeoTech](NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAA   notenoughkeys{@MOD_VERSION@} [NotEnoughKeys](NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter](OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   playerrugs{0.0.1} [Player Rugs](PlayerRugs-1.8.8-1.2.0.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.8-12} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
    UCHIJAAAA   progressiveautomation{1.6.35} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAA   Psi{beta-23} [Psi](Psi-beta-23.jar) 
    UCHIJAAAA   RandomThings{3.6.4} [Random Things](RandomThings-MC1.8.9-3.6.4.jar) 
    UCHIJAAAA   ResourceLoader{1.4} [Resource Loader](ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAAAA   rftools{4.22beta31} [RFTools](rftools-1.8.9-4.22beta31.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   soundfilters{0.8_for_1.8} [Sound Filters](SoundFilters-0.8_for_1.8.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.4} [Storage Drawers](StorageDrawers-1.8.9-2.4.4.jar) 
    UCHIJAAAA   thaumicinfusion{4.82} [Thaumic Infusion](ThaumicInfusion-1.8.9-4.82.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    UCHIJAAAA   denseores{1.0} [denseores](denseores-1.8-alpha-2.0.0.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  lumien.randomthings.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)

dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
List of loaded APIs: 
    * API_NEK (1.2.0) from NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar
    * Baubles|API (1.1.1.0) from Baubles-1.8.9-1.1.3.0.jar
    * BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.8.9-2.0.0-19.jar
    * BotaniaAPI (77) from Botania-unofficial.r1.8-299.jar
    * BuildCraftAPI|blocks (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|blueprints (1.5) from buildcraft-7.2.0.jar
    * BuildCraftAPI|boards (2.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|core (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|crops (1.1) from buildcraft-7.2.0.jar
    * BuildCraftAPI|enums (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|events (2.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|facades (1.1) from buildcraft-7.2.0.jar
    * BuildCraftAPI|filler (4.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|fuels (2.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|gates (4.1) from buildcraft-7.2.0.jar
    * BuildCraftAPI|items (1.1) from buildcraft-7.2.0.jar
    * BuildCraftAPI|library (2.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|lists (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|power (1.3) from buildcraft-7.2.0.jar
    * BuildCraftAPI|recipes (4.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|robotics (3.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|statements (1.1) from buildcraft-7.2.0.jar
    * BuildCraftAPI|tablet (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|tiles (1.2) from buildcraft-7.2.0.jar
    * BuildCraftAPI|tools (1.0) from buildcraft-7.2.0.jar
    * BuildCraftAPI|transport (4.1) from buildcraft-7.2.0.jar
    * CharsetAPI (0.1) from Charset-0.2.4-85343416c852285a595c4c6e.jar
    * CharsetAPI|Audio (0.0) from Charset-0.2.4-85343416c852285a595c4c6e.jar
    * CharsetAPI|Lib (0.2) from Charset-0.2.4-85343416c852285a595c4c6e.jar
    * CharsetAPI|Pipes (0.2) from Charset-0.2.4-85343416c852285a595c4c6e.jar
    * CharsetAPI|Wires (0.3) from Charset-0.2.4-85343416c852285a595c4c6e.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
    * ChiselsAndBitsAPI (1.8) from chiselsandbits-mc1.8.9-v1.8.11.jar
    * CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from Bookshelf-API-1.8.9-2.3.6.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
    * ComputerCraft|API (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|FileSystem (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Lua (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Media (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Peripheral (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Permissions (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Redstone (1.78) from ComputerCraft1.78.jar
    * ComputerCraft|API|Turtle (1.78) from ComputerCraft1.78.jar
    * CraftingTweaks|API (4.1) from craftingtweaks-mc1.8.9-3.0.52.jar
    * GameAnalyticsAPI (1.2) from AuraCascade-592.jar
    * HydCraft|API (1.0) from HydCraft-1.8.9-3.1.79-universal.jar
    * jeresources|API (0.4.0) from JustEnoughResources-1.8.9-0.4.0.jar
    * journeymap|client-api (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
    * journeymap|client-api-display (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
    * journeymap|client-api-event (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
    * journeymap|client-api-model (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
    * journeymap|client-api-util (1.1) from journeymap-1.8.9-5.1.5-unlimited.jar
    * JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.7.174.jar
    * McJtyLib (1.8.9-1.8.1beta8) from mcjtylib-1.8.9-1.8.1beta8.jar
    * PneumaticCraftApi (1.0) from PneumaticCraft-1.8.9-1.13.8-12-universal.jar
    * pressureAPI (1.3.0.25) from pressure-1.3.0.25-mc1.8.9.jar
    * PsiAPI (1) from Psi-beta-23.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.8.9-2.4.4.jar
    * Thaumcraft|API (5.2.2.0) from Thaumcraft-1.8.9-5.2.2.jar
    * WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['HNInfo'/1715489, l='New World', x=2081,22, y=9,49, z=113,70]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by CD4017BE** [comment]
From what I read in the crash report, the crash ocourred while creating the AntimatterBomb Entity. So the actual explosion didn't even start. It's probably som incompatibility with the new minecraft version. I will test it now myself and fix the bug.

**Comment by CD4017BE** [comment]
Jep, just changing the datawatcher Id from 2 to 5 fixed it. 
I have a litle crater in my testworld now :smile:.

**Comment by valveo** [comment]
I hope that i will have soon too :smile:

**Comment by CD4017BE** [comment]
Actually I didn't fix it I got another crash when trying it out on a normal (non dev environment) server. It seems that my access transformer isn't working. I'm getting Illegal Access Errors.
The same also happens when using the jetpack: The server console gets spammed with:
java.lang.IllegalAccessError: tried to access field net.minecraft.network.NetHandlerPlayServer.field_147365_f from class ...

The problem is that in forge-wiki doesn't state anything about how to use Access Transformers for MC-1.8.9

**Comment by CD4017BE** [comment]
Fixed: works on server and client
[release 4.0.1](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v4.0.1)

**Comment by valveo** [comment]
Thanks for fixing bug. Now I can blow my base :smile:
