### ISSUE TITLE
Antimatter Bomb Crash

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [CD4017BE/InductiveAutomation#11]
Seems different than the previous one you had reported. It crashed the server right as the shock wave got up to me. (I thought it had passed, oops.) Logging into the server simply reproduces the crash, presumably loading the chunk the bomb is in.

[crash-2016-06-27_18.43.25-server.txt](https://github.com/CD4017BE/InductiveAutomation/files/336136/crash-2016-06-27_18.43.25-server.txt)

**Comment by CD4017BE** [comment]
It seems that, after I rewrote the whole thing during MC-1.9.4 update, I simply forgot to finish the code, that replaces the AntimatterBomb with the raw version afterwards, Ups!
The next release for 1.9.4 will fix it.
