### ISSUE TITLE
crash when right clicking fluid tank with lava bucket

### ISSUE THREAD

**Issue by LlubNek** [CD4017BE/InductiveAutomation#12]
Minecraft crashed when I right clicked an Inductive Automation Fluid Tank with a lava bucket. I'm posting this here because though the exception occurred in Quark code, it occurred while I was interacting with your mod. I've submitted a bug report at their end too.

Here are the important bits:

```
java.lang.AbstractMethodError
    at vazkii.quark.base.handler.DropoffHandler.isValidChest(DropoffHandler.java:106)
    at vazkii.quark.management.feature.ChestButtons.initGui(ChestButtons.java:57)
...
    at cd4017be.lib.BlockGuiHandler.openGui(BlockGuiHandler.java:74)
    at cd4017be.lib.ModTileEntity.onActivated(ModTileEntity.java:57)
    at cd4017be.lib.TileBlock.func_180639_a(TileBlock.java:180)
...
```

crash report: [crash-2016-07-01_19.52.16-client.txt](https://github.com/CD4017BE/InductiveAutomation/files/344372/crash-2016-07-01_19.52.16-client.txt)
latest.log: [latest.log.txt](https://github.com/CD4017BE/InductiveAutomation/files/344374/latest.log.txt)

I'm using Quark-beta-35.jar, InductiveAutomation-1.9.4-5.1.0.jar, Forge 12.18.0.2005, Minecraft 1.10.2
The Quark issue is https://github.com/Vazkii/Quark/issues/94

**Comment by CD4017BE** [comment]
That's exactly the same issue with Quark I already fixed for 1.8.9 (just needs be build and released for 1.9.4). The tank can't be filled via right click with fluid containers (a feature I could maybe add), so the lava Bucket doesn't matter, I could have been any other (or even no) Item in your hand.
