### ISSUE TITLE
Please add dependency info for cd4017be lib

### ISSUE THREAD

**Issue by mezz** [CD4017BE/InductiveAutomation#14]
Please add something like this to your `@Mod()` section:
`dependencies = "required-after:CD4017BE_LIB`

https://github.com/CD4017BE/InductiveAutomation/blob/1.9.4/src/java/cd4017be/automation/Automation.java#L60

You may have to make cd4017be lib into a mod jar with a ModID as well, I wasn't able to find its ModID.
This way players will get a clear error message when the lib is missing, instead of a fatal crash.

**Comment by CD4017BE** [comment]
[CD4017BE_lib-4.3.0](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v4.3.0)
