### ISSUE TITLE
[Issue] 1.10.2 Startup Crash

### ISSUE THREAD

**Issue by accessdenied0** [CD4017BE/InductiveAutomation#15]
Hello @CD4017BE,

I used you mod on 1.10.2 now for a while until I decide to remove/change my own modpack. After I'm done with the removal and update of mods I noticed that it [crashed by startup](http://pastebin.com/8S5YR5iy)... 

Now here is the thing: I can't figure out what changed... it suddenly stopped working and I can only guess it might be the Forge version (Using: 12.18.1.2026, 12.18.1.2014 or 12.18.1.2011)

I hope you can help,

access_denied

**Comment by erindal** [comment]
@accessdenied0 Can you try again using the latest forge and versions of IA and the CD4017BE lib? Because its working fine for me, with Forge 2071.

**Comment by Amperthorpe** [comment]
I was having the same issue, I just tried with only Forge, the lib mod, and IA and it worked. Then I threw it into my modpack for 1.10.2 and I crashed with this http://pastebin.com/9RmL73tz
That's with newest forge, and definitely newest IA and Lib since they haven't had any updates in almost 2 months.

**Comment by erindal** [comment]
There's a bunch of core mods listed at the top, try removing those. If it works add them back one by one.

I do have a fairly comprehensive pack with IA in it running without a problem, so it's probably a specific mod you have.

**Comment by CD4017BE** [comment]
Found the problem: Another mod registered the fluid "steam" before mine so IA uses that instead of its own. But that other steam had no fluid block, so it crashed while registering the block models for its fluids.

**Comment by CD4017BE** [comment]
If you can't wait for the fix: Rename the mod's jar file, put an 'A' in front of the filename. This makes forge initialize IA before the other mod, so it uses its own steam.

**Comment by erindal** [comment]
That may or may not work on linux just so everyone is aware. There was a Minetweaker bug a while back where scripts don't load in order based on filename, so this may also be true with mod loading.

Thanks CD4017BE

**Comment by CD4017BE** [comment]
fixed by [v4.2.0](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v4.2.0)
