### ISSUE TITLE
JEI crash when trying to view a recipe

### ISSUE THREAD

**Issue by lOmicronl** [CD4017BE/InductiveAutomation#16]
Hello, mezz asked me to report this issue over here. Apparently it's a rare crash that randomly happens when trying to view recipes using JEI under Minecraft 1.10.x, because the recipe transfer handler API changed slightly.

I realize that Inductive Automation is not yet officially offered for Minecraft 1.10.x. Still, I hope this report helps you avoid the issue when the time comes to create such a version.

Details here: https://github.com/mezz/JustEnoughItems/issues/378

**Comment by CD4017BE** [comment]
I will be away for the next two weeks, but after that I will check it out.

**Comment by erindal** [comment]
Can also confirm this. I was viewing the recipe for wood casing when it crashed.
