### ISSUE TITLE
Xreliquary interaction crash

### ISSUE THREAD

**Issue by CJL48** [CD4017BE/InductiveAutomation#21]
Interacting with the gui while xreliquary is installed causes a crash (log attached).

Xreliquary also has an issue about this, it's a conflict between them registering void tears as crafting listeners, and code of this mod (among others) assuming that only players can be crafting listeners.

The Xreliquary issue: https://github.com/P3pp3rF1y/Reliquary/issues/186
[crash-2016-11-30_21.12.49-server.txt](https://github.com/CD4017BE/InductiveAutomation/files/623560/crash-2016-11-30_21.12.49-server.txt)

**Comment by CD4017BE** [comment]
Ok, for the next update I will then add "instanceof EntityPlayerMP"-checks wherever I use IContainerListeners.
