### ISSUE TITLE
No way to get 16kV for Gravitational Condenser?

### ISSUE THREAD

**Issue by KungLao666** [CD4017BE/InductiveAutomation#23]
Hello and sorry for my bad english.
Since InductiveAutomation-1.10.2-5.3.0 the Voltage Transformer is gone, i have no idea to get 16kV for the Gravitational Condeser to make bedrock.
I have tried all coils against each other, but the max. is 8kV.
Is this an issue or i'm a fool.

Thanks for help and troubleshooting

**Comment by CD4017BE** [comment]
You can still get higher voltages than 8kV using the Energy Link.

**Comment by KungLao666** [comment]
Thank you, my fault. ;)
