### ISSUE TITLE
Cables visual glitch

### ISSUE THREAD

**Issue by th4umiel** [CD4017BE/InductiveAutomation#24]
As you can see when looking at the cables sometimes show them transparent in some parts.
not really a bug but still would be nice to see this issue solved :)

![2017-03-11_17 43 49](https://cloud.githubusercontent.com/assets/17257735/25496009/b2cfd5b4-2b7f-11e7-84e9-3e695e3ac849.png)

**Comment by CD4017BE** [comment]
As part of version [5.3.4](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v5.3.4) this has also been fixed.
