### ISSUE TITLE
Please update to use latest lib version

### ISSUE THREAD

**Issue by Garagoth** [CD4017BE/InductiveAutomation#25]
Currently this required lib 4.3.4 <= x <= 4.4.0 while there is already version past that, required by Automated Redstone.
Also, when auto-installing deps via curse client (twitch) it gets latest version anyway...

**Comment by CD4017BE** [comment]
see: [issue at CD4017BE_lib](https://github.com/CD4017BE/CD4017BE_lib/issues/9)
