### ISSUE TITLE
[Issue] Quark-GUI Issue

### ISSUE THREAD

**Issue by accessdenied0** [CD4017BE/InductiveAutomation#3]
Hey @CD4017BE,

I tried your mod in my SSP world, but sadly I didn't come that far... It crashed soon I tried to open an GUI of one of your machines (Compression Assembler)...

Here is the Crash-report: http://pastebin.com/sSwcWreY

It seem to be a problem with Quark, which adds a "Storage to Chest" button to store and sort.

access_denied

**Comment by b0bst3r** [comment]
I posted this crash on Quark github not sure who's issue it is https://github.com/Vazkii/Quark/issues/36 disabling the chest buttons in Quark config stops the crash.
