### ISSUE TITLE
3d rendering in JEI

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/InductiveAutomation#4]
Sorry to use github to aska question but are you planning on making the blocks render in 3d in JEI?  At the moment it's difficult to tell what's a block and what's an item.

**Comment by CD4017BE** [comment]
After 1.9 update for some reason the rotation and scale of my Item models is broken. There are more than 200 files to fix, so I haven't done that jet. I'll probably write a small program that will fix them for me.

**Comment by CD4017BE** [comment]
fixed in 5.0.1 at least for the blocks, items are still rendered a bit too big when hold in hand or dropped.

**Comment by CD4017BE** [comment]
Items are also fixed now: [v5.1.0](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v5.1.0)
