### ISSUE TITLE
[1.9] Problems with the farm

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/InductiveAutomation#5]
Ok so this took me a while to figure out how to setup and it has some querks which maybe intended and me not understanding it right or maybe they are bugs.

In relation to growing/harvesting trees.

1 - I gave it spruce saplings and it planted them as oak (and they grew as oak)
2 - It does not seem to gather saplings or break leaves, they naturally decay even though I put a leaf block in the pipe gui for it to break them, so in the manual it says it gathers, this appears to be only the wood logs (not saplings and apples).
3 - It wont harvest logs outside of the assigned area so if you have a BIG oak tree grow is wont break all the log blocks, if you make the area bigger then it just plants saplings right up to this edge so that wont help, any way to avoid this?

So my question here is should the farm gather apples/saplings and restock itself, the tooltips in the GUI suggests it should do?

Is there anyway to make it not convert spruce saplings to oak saplings when planted?

**Comment by CD4017BE** [comment]
The thing with converting all sapling types into oak was actually a bug (something in minecraft's plant code changed during the update). I fixed it in upcoming 5.0.1.

About leaves harvesting, you have to set the filter to oak leaves and turn "also check silktouch dops" on. You could also use a magnet to pick up drops from decaying leaves.

And you can simply prevent the farm from planting saplings in the outer area by either removing the dirt or replacing it with a block that can't grow trees. And when growing oak trees you can prevent over sized trees by building a wall of any material that can't be replaced by leaves (for ex. glass or fences) around the farm area.

**Comment by b0bst3r** [comment]
ROFL I didn't even think of that (removing the dirt) thanks :) will the update be for 1.9 or 1.9.4
