### ISSUE TITLE
[1.9] Mass Storage chest sorting

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/InductiveAutomation#6]
Is there anyway to stop a middle click sort (another mod) from working on the mass storage chest.  I did it on autopilot and it basically took the stack in the first slot and split it into all the other slots wiping out everything in the other chest slots.

I know there's a button for sorting but I was on autopilot, if there's a way to disable things like that on your GUI it would be great.  If not just close this.

**Comment by CD4017BE** [comment]
Modded auto-sorting functions are usually implemented by just simulating normal mouse-click actions. And there is not really a way to detect whether such an action is done by a player or by an automated script. The only way would be to block every key or mouse event in the GUI to prevent these shortcuts. Which would of course also block JEI search / recipe viewing and possible other useful things.

Maybe that other mod has a config where you can blacklist GUIs like the Mass storage Chest.
