### ISSUE TITLE
Support for item handler capability

### ISSUE THREAD

**Issue by raoulvdberge** [CD4017BE/InductiveAutomation#7]
Currently pipes can't take items from a tile that uses Forge's capability system, it depends on IInventory.

Instead of checking for TileEntity you could check for IItemHandler (and still have compatibility with old IInventory) using this snippet:

``` java
    public static IItemHandler getItemHandler(TileEntity tile, EnumFacing side) {
        if (tile == null) {
            return null;
        }

        IItemHandler handler = tile.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, side);

        if (handler == null) {
            if (side != null && tile instanceof ISidedInventory) {
                handler = new SidedInvWrapper((ISidedInventory) tile, side);
            } else if (tile instanceof IInventory) {
                handler = new InvWrapper((IInventory) tile);
            }
        }

        return handler;
    }
```

Of course the pipes would need to use the IItemHandler interface.

**Comment by CD4017BE** [comment]
I just started changing everything into Forge's capability system:
Items, Fluids, Energy, Heat, Gas and maybe also some multiblock-machine related systems.

**Comment by CD4017BE** [comment]
[CD4017BE_lib-4.3.0](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v4.3.0)
