### ISSUE TITLE
Any chance of a 1.9.4 version

### ISSUE THREAD

**Issue by b0bst3r** [CD4017BE/InductiveAutomation#8]
Sorry to ask in a github but we're only waiting for you :D I don't want to remove the mod it has so many cool toys.

Speaking to the other modders it's not a massive job to update.  Any thoughts on it CD?

**Comment by CD4017BE** [comment]
If the minecraft and forge update from 1.9 to 1.9.4 didn't have serious changes in sourcecode, the 1.9 versions of my mods should also be usable with 1.9.4. However I haven't  tested that yet.

**Comment by b0bst3r** [comment]
http://i.imgur.com/PLCnY3o.png

**Comment by CD4017BE** [comment]
That's very strange because the mod never tells forge which version it requires. The whole jar file of v5.0.1 doesn't even contain the string '1.9' in any of its classes or resources. Could you please give me the 'fml-client-latest.log' mentioned in your screenshot.

**Comment by b0bst3r** [comment]
http://pastebin.com/T0bBNraX

Line 167 is you

**Comment by CD4017BE** [comment]
They changed a bit more than I thought. But it's ported to MC-1.9.4 now: [v5.1.0](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v5.1.0)
